default_stages: [ commit ]
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        language_version: python3.10
        types: [ python ]
        args: [ -v, --profile=black]

      - id: black
        name: black
        entry: black --config ./.black .
        language: system
        types: [python]
        pass_filenames: false


      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 .
        language: system
        types: [python]
        pass_filenames: false