version: "3.7"

services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh entrypoint.sh
    volumes:
      - .:/fast_flat
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
     - db
    links:
       - "db:db"

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - .env

  nginx:
    build: ./docker_configs/nginx/
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
