"""status

Revision ID: 14c41e73990f
Revises: a63fba2eeabc
Create Date: 2023-04-24 15:18:46.101200

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "14c41e73990f"
down_revision = "a63fba2eeabc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "renting",
        sa.Column(
            "status",
            sa.Boolean(),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "renting",
        sa.Column(
            "status",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
