"""is_active

Revision ID: 0c0e634ee7b0
Revises: f206b061c4d6
Create Date: 2023-01-19 12:45:52.858791

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c0e634ee7b0"
down_revision = "f206b061c4d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flat", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.add_column(
        "renting",
        sa.Column(
            "is_approved",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("renting", "is_approved")
    op.alter_column(
        "flat", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
