"""add photo to flat

Revision ID: 0db03cadc26e
Revises: 0c0e634ee7b0
Create Date: 2023-04-15 14:23:50.677391

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0db03cadc26e"
down_revision = "0c0e634ee7b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
