"""FileField to url

Revision ID: b1f8ff7cddc0
Revises: 0db03cadc26e
Create Date: 2023-04-15 16:42:41.427338

"""

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b1f8ff7cddc0"
down_revision = "0db03cadc26e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "flat_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
        sa.Column(
            "photo", sqlalchemy_utils.types.url.URLType(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["flat_id"],
            ["flat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_photo_id"), "photo", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photo_id"), table_name="photo")
    op.drop_table("photo")
    # ### end Alembic commands ###
