"""

Revision ID: 726b187ef206
Revises: 14c41e73990f
Create Date: 2024-03-17 06:57:46.345699

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "726b187ef206"
down_revision = "14c41e73990f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
