"""

Revision ID: b5f9c504be03
Revises: 726b187ef206
Create Date: 2024-03-17 06:58:48.392998

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b5f9c504be03"
down_revision = "726b187ef206"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
