"""empty message

Revision ID: 1cd963bd9305
Revises: b5f9c504be03
Create Date: 2025-05-18 11:51:33.167682

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1cd963bd9305"
down_revision = "b5f9c504be03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("flat_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.CheckConstraint("type <= 3", name="check_type_max"),
        sa.CheckConstraint("type > 0", name="check_type_positive"),
        sa.ForeignKeyConstraint(
            ["flat_id"],
            ["flat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promotion_id"), "promotion", ["id"], unique=True)
    op.alter_column(
        "flat",
        "cost",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flat",
        "cost",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_promotion_id"), table_name="promotion")
    op.drop_table("promotion")
    # ### end Alembic commands ###
